-- MySQL Script generated by MySQL Workbench
-- vie 01 nov 2019 20:31:12 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AFA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AFA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AFA` DEFAULT CHARACTER SET utf8 ;
USE `AFA` ;

-- -----------------------------------------------------
-- Table `AFA`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Equipo` (
  `id_Equipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_Fundacion` DATETIME NULL,
  `Nombre_Presidente` VARCHAR(45) NULL,
  `Apellido_Presidente` VARCHAR(45) NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero_Puerta` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` INT NOT NULL,
  `Telefono` INT NULL,
  `Email` INT NULL,
  `En_Primera` INT NULL,
  PRIMARY KEY (`id_Equipo`),
  INDEX `fk_Equipo_Provincia_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Equipo_Provincia`
    FOREIGN KEY (`Provincia`)
    REFERENCES `AFA`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `AFA`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Jugador` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Calle` VARCHAR(45) NULL,
  `Numero_Puerta` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` INT NOT NULL,
  `Email` INT NULL,
  `Telefono` INT NULL,
  `Equipo_Nombre` VARCHAR(45) NULL,
  `Historial` INT NULL,
  `Peso` INT NULL,
  `Altura` INT NULL,
  `Posicion_En_Cancha` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_Jugador_Provincia1_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Jugador_Provincia1`
    FOREIGN KEY (`Provincia`)
    REFERENCES `AFA`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Tecnico` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Calle` VARCHAR(45) NULL COMMENT '\n\n\n',
  `Numero_Puerta` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` INT NOT NULL DEFAULT 0,
  `Telefono` INT NULL,
  `Email` INT NULL,
  `Equipo_Nombre` VARCHAR(45) NULL,
  `Historial` INT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_Tecnico_Provincia1_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Tecnico_Provincia1`
    FOREIGN KEY (`Provincia`)
    REFERENCES `AFA`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Tel_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Tel_Equipo` (
  `id_Equipo` INT NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  INDEX `fk_Tel_Equipo_Equipo1_idx` (`id_Equipo` ASC),
  CONSTRAINT `fk_Tel_Equipo_Equipo1`
    FOREIGN KEY (`id_Equipo`)
    REFERENCES `AFA`.`Equipo` (`id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Mail_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Mail_Equipo` (
  `id_Equipo` INT NOT NULL,
  `Mail_Equipo` VARCHAR(45) NULL,
  INDEX `fk_Mail_Equipo_Equipo1_idx` (`id_Equipo` ASC),
  CONSTRAINT `fk_Mail_Equipo_Equipo1`
    FOREIGN KEY (`id_Equipo`)
    REFERENCES `AFA`.`Equipo` (`id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Mail_DT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Mail_DT` (
  `DNI` INT NOT NULL,
  `Mail_DT` VARCHAR(45) NULL,
  INDEX `fk_Mail_DT_Tecnico1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Mail_DT_Tecnico1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Tecnico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Tel_DT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Tel_DT` (
  `DNI` INT NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  INDEX `fk_Tel_DT_Tecnico1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Tel_DT_Tecnico1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Tecnico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Historial_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Historial_Equipo` (
  `id_Equipo` INT NOT NULL,
  `Desde` DATE NULL,
  `Hasta` DATE NULL,
  INDEX `fk_Historial_Equipo_Equipo1_idx` (`id_Equipo` ASC),
  CONSTRAINT `fk_Historial_Equipo_Equipo1`
    FOREIGN KEY (`id_Equipo`)
    REFERENCES `AFA`.`Equipo` (`id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Historial_DT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Historial_DT` (
  `DNI` INT NOT NULL,
  `Equipo_Nombre` VARCHAR(45) NULL,
  `Desde` DATE NULL,
  `Hasta` DATE NULL,
  INDEX `fk_Historial_DT_Tecnico1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Historial_DT_Tecnico1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Tecnico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Tecnico_has_Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Tecnico_has_Jugador` (
  `Tecnico_DNI` INT NOT NULL,
  `Jugador_DNI` INT NOT NULL,
  PRIMARY KEY (`Tecnico_DNI`, `Jugador_DNI`),
  INDEX `fk_Tecnico_has_Jugador_Jugador1_idx` (`Jugador_DNI` ASC),
  INDEX `fk_Tecnico_has_Jugador_Tecnico1_idx` (`Tecnico_DNI` ASC),
  CONSTRAINT `fk_Tecnico_has_Jugador_Tecnico1`
    FOREIGN KEY (`Tecnico_DNI`)
    REFERENCES `AFA`.`Tecnico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tecnico_has_Jugador_Jugador1`
    FOREIGN KEY (`Jugador_DNI`)
    REFERENCES `AFA`.`Jugador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Mail_Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Mail_Jugador` (
  `DNI` INT NOT NULL,
  `Mail_Jugador` VARCHAR(45) NULL,
  INDEX `fk_Mail_Jugador_Jugador1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Mail_Jugador_Jugador1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Jugador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Tel_Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Tel_Jugador` (
  `DNI` INT NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  INDEX `fk_Tel_Jugador_Jugador1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Tel_Jugador_Jugador1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Jugador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Historial_Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Historial_Jugador` (
  `DNI` INT NOT NULL,
  `Equipo_Nombre` VARCHAR(45) NULL,
  `Desde` DATE NULL,
  `Hasta` DATE NULL,
  INDEX `fk_Historial_Jugador_Jugador1_idx` (`DNI` ASC),
  CONSTRAINT `fk_Historial_Jugador_Jugador1`
    FOREIGN KEY (`DNI`)
    REFERENCES `AFA`.`Jugador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Equipo_has_Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Equipo_has_Jugador` (
  `Equipo_id_Equipo` INT NOT NULL,
  `Jugador_DNI` INT NOT NULL,
  PRIMARY KEY (`Equipo_id_Equipo`, `Jugador_DNI`),
  INDEX `fk_Equipo_has_Jugador_Jugador1_idx` (`Jugador_DNI` ASC),
  INDEX `fk_Equipo_has_Jugador_Equipo1_idx` (`Equipo_id_Equipo` ASC),
  CONSTRAINT `fk_Equipo_has_Jugador_Equipo1`
    FOREIGN KEY (`Equipo_id_Equipo`)
    REFERENCES `AFA`.`Equipo` (`id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_has_Jugador_Jugador1`
    FOREIGN KEY (`Jugador_DNI`)
    REFERENCES `AFA`.`Jugador` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AFA`.`Equipo_has_Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AFA`.`Equipo_has_Tecnico` (
  `Equipo_id_Equipo` INT NOT NULL,
  `Tecnico_DNI` INT NOT NULL,
  PRIMARY KEY (`Equipo_id_Equipo`, `Tecnico_DNI`),
  INDEX `fk_Equipo_has_Tecnico_Tecnico1_idx` (`Tecnico_DNI` ASC),
  INDEX `fk_Equipo_has_Tecnico_Equipo1_idx` (`Equipo_id_Equipo` ASC),
  CONSTRAINT `fk_Equipo_has_Tecnico_Equipo1`
    FOREIGN KEY (`Equipo_id_Equipo`)
    REFERENCES `AFA`.`Equipo` (`id_Equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_has_Tecnico_Tecnico1`
    FOREIGN KEY (`Tecnico_DNI`)
    REFERENCES `AFA`.`Tecnico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
